# Generated by Django 5.1.7 on 2025-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekstrakurikuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('deskripsi', models.TextField()),
                ('instagram', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('youtube', models.CharField(max_length=250)),
                ('tiktok', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
                ('image', models.ImageField(default='ekstrakurikuler/default.jpg', upload_to='ekstrakurikuler/')),
            ],
        ),
    ]
