# Generated by Django 5.1.7 on 2025-04-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AddField(
            model_name='profile',
            name='kode_pos',
            field=models.CharField(default='12345', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='telepon',
            field=models.CharField(default='1234567890', max_length=15),
        ),
    ]
