# Generated by Django 5.1.7 on 2025-04-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_profile_website_profile_kode_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kode_pos',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telepon',
            field=models.CharField(max_length=15),
        ),
    ]
