# Generated by Django 5.1.7 on 2025-04-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_profile_kode_pos_alter_profile_telepon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/default.jpg', upload_to='post/'),
        ),
    ]
