# Generated by Django 5.1.7 on 2025-04-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenagaPendidik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('jabatan', models.CharField(max_length=100)),
                ('image', models.ImageField(default='tenaga_pendidik/default.jpg', upload_to='tenaga_pendidik/')),
            ],
        ),
    ]
